
Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/focal64"

  config.vm.network "forwarded_port", guest: 80, host: 20080
  config.vm.network "forwarded_port", guest: 9443, host: 29443

  config.vm.synced_folder "./store", "/opt"

  config.vm.provider "virtualbox" do |vb|
    vb.name = "lab-3-1"
    vb.memory = "2048"
  end
  
  config.vm.provision "shell", inline: <<-SHELL
    export DEBIAN_FRONTEND=noninteractive
    apt-get update
    apt-get remove -y docker docker-engine docker.io containerd runc
    apt-get remove -y multipath-tools --purge
    # Install docker
    apt-get install -y ca-certificates curl gnupg lsb-release
    curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
    echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | tee /etc/apt/sources.list.d/docker.list > /dev/null
    apt-get update
    apt-get install -y docker-ce docker-ce-cli containerd.io
    # post-installation steps
    usermod -aG docker vagrant
  SHELL

  config.vm.provision "shell", inline: <<-SHELL
    # install  Portainer
    #docker volume create portainer_data
    docker run -d -p 8000:8000 -p 9443:9443 --name portainer \
      --restart=always \
      -v /var/run/docker.sock:/var/run/docker.sock \
      -v /opt/portainer_data:/data \
      portainer/portainer-ce:2.11.1
    SHELL

end