# DOR3 - PROJEKT

vmmemory = 1024
numworkers = 2
vm1_ip = "192.168.10.2"

instances = []

(1..numworkers).each do |n|
  instances.push({:name => "worker#{n}", :ip => "192.168.10.#{n+2}"})
end

# Vagrant version requirement
Vagrant.require_version ">= 1.8.4"

Vagrant.configure("2") do |config|

  config.vm.provider "virtualbox" do |v|
    v.memory = vmmemory
  end

  config.vm.define "vm-1" do |i|
    i.vm.box = "ubuntu/focal64"
    i.vm.hostname = "vm-1"
    i.vm.network "forwarded_port", guest: 80, host: 20080
    i.vm.network "private_network", ip: "#{vm1_ip}"
    i.vm.provision "shell", inline: <<-SHELL
      export DEBIAN_FRONTEND=noninteractive
      apt-get update
      apt-get install -y nginx mc iptraf net-tools links
      cp /vagrant/files/nginx/nginx.conf /etc/nginx/nginx.conf
      cp /vagrant/files/nginx/default /etc/nginx/sites-enabled/default
      systemctl reload nginx.service
    SHELL
  end

  instances.each do |instance|
    config.vm.define instance[:name] do |i|
      i.vm.box = "ubuntu/focal64"
      i.vm.hostname = instance[:name]
      i.vm.network "private_network", ip: "#{instance[:ip]}"
      i.vm.provision "shell", inline: <<-SHELL
        export DEBIAN_FRONTEND=noninteractive
        apt-get update
        apt-get install -y apache2
        cp /vagrant/files/index.html /var/www/html/index.html
        echo `hostname` >> /var/www/html/index.html
      SHELL
    end
  end
end
